version: "3.8"
services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-3080}
      - MONGO_URI=${MONGO_URI:-mongodb://127.0.0.1:27017/LibreChat}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT:-http://localhost:3080}
      - DOMAIN_SERVER=${DOMAIN_SERVER:-http://localhost:3080}
      - NO_INDEX=${NO_INDEX:-true}
      - CONSOLE_JSON=${CONSOLE_JSON:-false}
      - DEBUG_LOGGING=${DEBUG_LOGGING:-true}
      - DEBUG_CONSOLE=${DEBUG_CONSOLE:-false}
      - PROXY=${PROXY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-user_provided}
      - BINGAI_TOKEN=${BINGAI_TOKEN:-user_provided}
      - GOOGLE_KEY=${GOOGLE_KEY:-user_provided}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-user_provided}
      - DEBUG_OPENAI=${DEBUG_OPENAI:-false}
      - ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY:-user_provided}
      - DEBUG_PLUGINS=${DEBUG_PLUGINS:-true}
      - CREDS_KEY=${CREDS_KEY:-f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0}
      - CREDS_IV=${CREDS_IV:-e2341419ec3dd3d19b13a1a87fafcbfb}
      - AZURE_AI_SEARCH_SERVICE_ENDPOINT=${AZURE_AI_SEARCH_SERVICE_ENDPOINT:-}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME:-}
      - AZURE_AI_SEARCH_API_KEY=${AZURE_AI_SEARCH_API_KEY:-}
      - AZURE_AI_SEARCH_API_VERSION=${AZURE_AI_SEARCH_API_VERSION:-}
      - AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE=${AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE:-}
      - AZURE_AI_SEARCH_SEARCH_OPTION_TOP=${AZURE_AI_SEARCH_SEARCH_OPTION_TOP:-}
      - AZURE_AI_SEARCH_SEARCH_OPTION_SELECT=${AZURE_AI_SEARCH_SEARCH_OPTION_SELECT:-}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY:-}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID:-}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY:-}
      - SD_WEBUI_URL=${SD_WEBUI_URL:-http://host.docker.internal:7860}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - TRAVERSAAL_API_KEY=${TRAVERSAAL_API_KEY:-}
      - WOLFRAM_APP_ID=${WOLFRAM_APP_ID:-}
      - ZAPIER_NLA_API_KEY=${ZAPIER_NLA_API_KEY:-}
      - SEARCH=${SEARCH:-true}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_HOST=${MEILI_HOST:-http://0.0.0.0:7700}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt}
      - OPENAI_MODERATION=${OPENAI_MODERATION:-false}
      - OPENAI_MODERATION_API_KEY=${OPENAI_MODERATION_API_KEY:-}
      - BAN_VIOLATIONS=${BAN_VIOLATIONS:-true}
      - BAN_DURATION=${BAN_DURATION:-1000 * 60 * 60 * 2}
      - BAN_INTERVAL=${BAN_INTERVAL:-20}
      - LOGIN_VIOLATION_SCORE=${LOGIN_VIOLATION_SCORE:-1}
      - REGISTRATION_VIOLATION_SCORE=${REGISTRATION_VIOLATION_SCORE:-1}
      - CONCURRENT_VIOLATION_SCORE=${CONCURRENT_VIOLATION_SCORE:-1}
      - MESSAGE_VIOLATION_SCORE=${MESSAGE_VIOLATION_SCORE:-1}
      - NON_BROWSER_VIOLATION_SCORE=${NON_BROWSER_VIOLATION_SCORE:-20}
      - LOGIN_MAX=${LOGIN_MAX:-7}
      - LOGIN_WINDOW=${LOGIN_WINDOW:-5}
      - REGISTER_MAX=${REGISTER_MAX:-5}
      - REGISTER_WINDOW=${REGISTER_WINDOW:-60}
      - LIMIT_CONCURRENT_MESSAGES=${LIMIT_CONCURRENT_MESSAGES:-true}
      - CONCURRENT_MESSAGE_MAX=${CONCURRENT_MESSAGE_MAX:-2}
      - LIMIT_MESSAGE_IP=${LIMIT_MESSAGE_IP:-true}
      - MESSAGE_IP_MAX=${MESSAGE_IP_MAX:-40}
      - MESSAGE_IP_WINDOW=${MESSAGE_IP_WINDOW:-1}
      - LIMIT_MESSAGE_USER=${LIMIT_MESSAGE_USER:-false}
      - MESSAGE_USER_MAX=${MESSAGE_USER_MAX:-40}
      - MESSAGE_USER_WINDOW=${MESSAGE_USER_WINDOW:-1}
      - ILLEGAL_MODEL_REQ_SCORE=${ILLEGAL_MODEL_REQ_SCORE:-5}
      - CHECK_BALANCE=${CHECK_BALANCE:-false}
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN:-false}
      - ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION:-false}
      - SESSION_EXPIRY=${SESSION_EXPIRY:-1000 * 60 * 15}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY:-(1000 * 60 * 60 * 24) * 7}
      - JWT_SECRET=${JWT_SECRET:-16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID:-}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET:-}
      - DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL:-/oauth/discord/callback}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID:-}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET:-}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL:-/oauth/facebook/callback}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL:-/oauth/github/callback}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL:-/oauth/google/callback}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID:-}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET:-}
      - OPENID_ISSUER=${OPENID_ISSUER:-}
      - OPENID_SESSION_SECRET=${OPENID_SESSION_SECRET:-}
      - OPENID_SCOPE=${OPENID_SCOPE:-"openid profile email"}
      - OPENID_CALLBACK_URL=${OPENID_CALLBACK_URL:-/oauth/openid/callback}
      - OPENID_REQUIRED_ROLE=${OPENID_REQUIRED_ROLE:-}
      - OPENID_REQUIRED_ROLE_TOKEN_KIND=${OPENID_REQUIRED_ROLE_TOKEN_KIND:-}
      - OPENID_REQUIRED_ROLE_PARAMETER_PATH=${OPENID_REQUIRED_ROLE_PARAMETER_PATH:-}
      - OPENID_BUTTON_LABEL=${OPENID_BUTTON_LABEL:-}
      - OPENID_IMAGE_URL=${OPENID_IMAGE_URL:-}
      - EMAIL_SERVICE=${EMAIL_SERVICE:-}
      - EMAIL_HOST=${EMAIL_HOST:-}
      - EMAIL_PORT=${EMAIL_PORT:-25}
      - EMAIL_ENCRYPTION=${EMAIL_ENCRYPTION:-}
      - EMAIL_ENCRYPTION_HOSTNAME=${EMAIL_ENCRYPTION_HOSTNAME:-}
      - EMAIL_ALLOW_SELFSIGNED=${EMAIL_ALLOW_SELFSIGNED:-}
      - EMAIL_USERNAME=${EMAIL_USERNAME:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME:-}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@librechat.ai}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY:-}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN:-}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID:-}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID:-}
      - APP_TITLE=${APP_TITLE:-LibreChat}
      - HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL:-https://librechat.ai}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
  client:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: prod-stage
    container_name: LibreChat-NGINX
    ports:
      - 3002:80
    depends_on:
      - api
    restart: always
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data
  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  pgdata2:
